export interface G3Code {
  prefixObjectKey: string,
  id: string,
  objectType: string,
  objectKey: string,
  changeLogComment: string|null,
  createdBy: string|null,
  createdDate: number|null,
  modifiedBy: string|null,
  modifiedDate: number|null,
  // modifiedTimestamp: string|null,
  createdByName: string|null,
  modifiedByName: string|null,
  createdDateField: number|null,
  modifiedDateField: number|null,
  createdMode: string|null,
  modifiedMode: string|null,
  recordIndex: number|null,
  readOnly: boolean,
  backgroundUpdate: boolean,
  g3Code: string,
  g2Code: string,
  g1Code: string,
  description: string,
  companyCode: string|null,
  blRequirements: string|null,
  blAddressId: number|null,
  activationStatus: string|null,
  blAddress: string|null,
  documentAddressFormat: string|null,
  companyName: string|null,
  g1CodeDescription: string|null,
  g2CodeDescription: string|null,
  RowId: string,
  // highlight: null
}