export interface Location {
  prefixObjectKey: string;
  id: string;
  objectType: string;
  objectKey: string;
  changeLogComment: string|null;
  createdBy: string|null;
  createdDate: number|null;
  modifiedBy: string|null;
  modifiedDate: number|null;
  //modifiedTimestamp: null;
  createdByName: string|null;
  modifiedByName: string|null;
  createdDateField: number|null;
  modifiedDateField: number|null;
  createdMode: string|null;
  modifiedMode: string|null;
  recordIndex: number|null;
  readOnly: boolean;
  backgroundUpdate: boolean;
  locationCode: string;
  locationName: string;
  locationType: string;
  houseNumber: string|null;
  street: string|null;
  //openingHoursFrom: null;
  //openingHoursTo: null;
  address: string|null;
  houseNumberAddition: string|null;
  zip: string|null;
  g1Code: string;
  g2Code: string;
  g3Code:string;
  g4Code: string;
  geoLocation: string|null;
  locationSearch:string;
  activationStatus: string|null;
  cfsyncStatus: string|null;
  countryName: string|null;
  g4CodeDescription: string|null;
  g3CodeDescription: string|null;
  g2CodeDescription: string|null;
  g1CodeDescription: string|null;
  locationTypeValue: string|null;
  timeZone: string|null;
  RowId: string;
  //highlight: null;
}
