export interface MenuItem {
  prefixObjectKey?: any,
  id?: string,
  objectType?: string,
  objectKey?: any,
  changeLogComment?: any,
  createdBy?: any,
  createdDate?: any,
  modifiedBy?: any,
  modifiedDate?: any,
  modifiedTimestamp?: any,
  createdByName?: any,
  modifiedByName?: any,
  createdDateField?: any,
  modifiedDateField?: any,
  createdMode?: any,
  modifiedMode?: any,
  recordIndex?: number,
  readOnly?: boolean,
  backgroundUpdate?: boolean,
  display_name?: string,
  state?: string,
  menu_order?: number,
  parent_menu_id?: any,
  sub_menu_id?: any,
  default_state?: any,
  module_name?: string,
  menu_id?: string,
  menu?: string[],
  sub_menus?: MenuItem[],
  RowId?: any,
  highlight: null
}

/*
 {
  prefixObjectKey: null,
  id: '506',
  objectType: 'ApplicationMenuBase',
  objectKey: null,
  changeLogComment: null,
  createdBy: null,
  createdDate: null,
  modifiedBy: null,
  modifiedDate: null,
  modifiedTimestamp: null,
  createdByName: null,
  modifiedByName: null,
  createdDateField: null,
  modifiedDateField: null,
  createdMode: null,
  modifiedMode: null,
  recordIndex: 0,
  readOnly: false,
  backgroundUpdate: false,
  display_name: 'Maintenance',
  state: '/finance/maintenance',
  menu_order: 6,
  parent_menu_id: null,
  sub_menu_id: null,
  default_state: null,
  module_name: 'Finance',
  menu_id: 'FINANCE_MAINTAINENCE',
  menu: [
    'FINANCE_MAINTAINENCE.GENERAL_SETTINGS',
  ],
  sub_menus: [
    {
      prefixObjectKey: null,
      id: '50601',
      objectType: 'ApplicationMenuBase',
      objectKey: null,
      changeLogComment: null,
      createdBy: null,
      createdDate: null,
      modifiedBy: null,
      modifiedDate: null,
      modifiedTimestamp: null,
      createdByName: null,
      modifiedByName: null,
      createdDateField: null,
      modifiedDateField: null,
      createdMode: null,
      modifiedMode: null,
      recordIndex: 0,
      readOnly: false,
      backgroundUpdate: false,
      display_name: 'General Settings',
      state: '/finance/maintenance/general-settings',
      menu_order: 1,
      parent_menu_id: 'FINANCE_MAINTAINENCE',
      sub_menu_id: null,
      default_state: null,
      module_name: null,
      menu_id: 'FINANCE_MAINTAINENCE.GENERAL_SETTINGS',
      menu: [],
      sub_menus: [],
      RowId: null,
      highlight: null
    },
  ],
  RowId: null,
  highlight: null
}
*/